replicaCount: 1

image:
  repository: johnsonbv/react-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: frontend.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

