replicaCount: 1

image:
  repository: johnsonbv/java-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: backend.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

