apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:admin, *, *, *, allow
    u, admin, role:admin
  policy.default: role:readonly
  policy.matchMode: glob

