apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-sm
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: spring-backend
  namespaceSelector:
    matchNames:
    - default # or your app's namespace
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s

