apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-backend-monitor
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: spring-backend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s

