apiVersion: v1
kind: Service
metadata:
  name: spring-metrics-svc
  labels:
    app: spring-backend
spec:
  selector:
    app: spring-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

