apiVersion: v1
kind: Service
metadata:
  name: spring-backend
  labels:
    app: spring-backend
spec:
  selector:
    app: spring-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080

